### ISSUE TITLE
Slider doesn't update when switching between two datasets.

### ISSUE THREAD

**Issue by ebower12** [iozbeyli/react-semantic-ui-range#7]
I have two objects that I'm switching between, and the slider pulls it's starting position from a property of the objects. Changing from one object to another changes the data the slider is pulling, but the position of the slider doesn't update to reflect the change. The labels in these screenshots are pulling from the same data and property so the data is definitely updating.

<img width="255" alt="screen shot 2018-09-13 at 12 29 59 pm" src="https://user-images.githubusercontent.com/32675636/45502001-ced2fa80-b750-11e8-98b5-98ad5861758a.png">

<img width="253" alt="screen shot 2018-09-13 at 12 30 07 pm" src="https://user-images.githubusercontent.com/32675636/45502008-d397ae80-b750-11e8-9aa2-7e287a4ca98f.png">

Here's how I've coded the slider for reference
```
<div id="weight-slider-div">
    <div id="weight-slider">
         <Slider
             color="blue"
             settings={{
                  min: 0,
                  max: 10,
                  start: question.weight,
                  step: 1,
                  onChange: (value) => { this.setQuestionWeight(question, value, pendingWeighting) },
             }}
        />
     </div>
     <Label color="blue">{question.weight}</Label>
 </div>
```

**Comment by iozbeyli** [comment]
Please use value instead of start for external changes. Detailed examples are on [https://iozbeyli.github.io/react-semantic-ui-range/](url). Sorry for the late response.
