### ISSUE TITLE
Discrete "mode" not locking to position

### ISSUE THREAD

**Issue by jonasfrid** [iozbeyli/react-semantic-ui-range#8]
Great work!

However, I can't get the discrete mode (setting step: 1) to get the slider to lock to position (as the first item in the demo: https://iozbeyli.github.io/react-semantic-ui-range/)

Here's my code, any idea what I'm doing wrong?
`<Slider color='black' inverted={false}
                settings={
                  start: this.state.value,
                  min: 0,
                  max: 5,
                  step:1,
                  onChange: (value, meta) => {
                    console.log('test', value, meta);
                    if (meta.triggeredByUser) {
                      this.setState({
                        value: value
                      })
                    }
                  }
              />`

**Comment by iozbeyli** [comment]
Thank you. You need to add discrete to your props.
`<Slider discrete color='black' inverted={false} settings={ start: this.state.value, min: 0, max: 5, step:1, onChange: (value, meta) => { console.log('test', value, meta); if (meta.triggeredByUser) { this.setState({ value: value }) } } />`

**Comment by jonasfrid** [comment]
Silly me, didn't spot that :)
Thanks!
